version: '3'
services:
  # rhel_personal:
  #   image: registry.access.redhat.com/ubi8/ubi:latest
  #   container_name: rhel_personal
  #   ports:
  #     - "8080:80"
  #   command: /bin/bash -c "while true; do echo hello world; sleep 10; done"
  #   networks:
  #     - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
